[2492] Trial page redesign
QualityUnit/liveagent-theme pull request #1008
Opened 2023-01-31 13:48 UTC by rlaco-qualityunit

**Changes proposed in this Pull Request**
Describe what was changed in the Pull Request

**Testing instructions**
Describe how and what should be tested by a Tester

**Checklist**
- [ ] My code follows the style guidelines of this project
- [ ] My commits follow the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#2492

2023-02-01 07:50 UTC, jremen approved these changes

2023-02-03 08:17 UTC, mvstepanek commented
@rlaco-qualityunit, please fix those tooltips and horizontal scroll on mobile
<img width="521" alt="Screenshot 2023-02-03 at 09 11 57" src="https://user-images.githubusercontent.com/17085174/216547663-ea120245-647e-44dd-b3b2-9463359ce174.png">
<img width="402" alt="Screenshot 2023-02-03 at 09 10 47" src="https://user-images.githubusercontent.com/17085174/216547659-81c635f5-9118-4021-aff3-0ff669b4c8dd.png">
<img width="472" alt="Screenshot 2023-02-03 at 09 15 00" src="https://user-images.githubusercontent.com/17085174/216547784-8a10b3ba-0ae5-437a-9039-769d9b70f135.png">

2023-02-03 12:48 UTC, mvstepanek requested changes
Please, implement those comments above.

2023-02-09 13:59 UTC, rlaco-qualityunit commented
@jremen please review new popper js tooltips

2023-02-20 09:03 UTC, jremen approved these changes

2023-02-20 11:22 UTC, mvstepanek approved these changes

2023-02-20 11:22 UTC, merged