[1630] AI Features Promotions
QualityUnit/liveagent-theme pull request #1438
Opened 2023-07-27 16:02 UTC by thujcak

**Changes proposed in this Pull Request**

added new element for elementor, added announcement bar on HP added new label to pricing list

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] My commits follow the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#1630

2023-07-31 12:24 UTC, jremen requested changes
use relative units, move animations into separate _animations.scss file

2023-07-31 12:24 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +$Announcement_bar_height: 120px;
use relative units

2023-07-31 12:24 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +					background: linear-gradient(291deg, #ffd3b8 0%, #050505 100%);
use variables we already have, $black instead of #050505

2023-07-31 12:24 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +						width: 100%;
use @include square(100%). Or better, posZero (and remove width and height)

2023-07-31 12:24 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +						@include square(24px);
use relative units

2023-07-31 12:24 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +						top: 10px;
use relative units

2023-07-31 12:24 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +						top: 23px;
use relative units

2023-07-31 12:24 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +			#app {
preferably do not use ids for styling

2023-07-31 12:24 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +		@keyframes slideDown {
move this into common/_animations.scss

2023-07-31 12:24 UTC, jremen commented on assets/styles/components/_AiWhisperAssistent.scss
> +		padding: 5em 40px;
use relative units

2023-07-31 12:24 UTC, jremen commented on assets/styles/components/_AiWhisperAssistent.scss
> +			padding: 65px 120px;
use relative units

2023-07-31 12:24 UTC, jremen commented on assets/styles/layouts/_ComparePlansNew.scss
> +				font-size: 12px;
use relative units, 0.75rem

2023-07-31 12:24 UTC, jremen commented on assets/styles/layouts/_ComparePlansNew.scss
> +				padding: 2px 9px 2px 9px;
use relative units

2023-08-02 06:34 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +@forward "../common/animations";
no need to call it here, it's already loaded in main app.scss and Elementor.scss files. Remove line for animations file

2023-08-02 06:35 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +					z-index: 999;
if not needed, avoid high z-index and use only slightly bigger. Otherwise it might conflict with other elements.
If you just need to show it above parent, use z-index: 2 or 3, it usually is good enough

2023-08-02 06:35 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +							z-index: 9;
same, try lower z-index values

2023-08-02 06:35 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +								width: 100%;
@include square(100%))

2023-08-02 06:36 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +						right: 10px;
relative units

2023-08-02 06:36 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +						z-index: 20;
z-index too high

2023-08-02 06:36 UTC, jremen commented on assets/styles/components/AnnouncementBar.scss
> +									font-size: 1.4375em;
do we really need such absurd values? For font size, always use rem units.

2023-08-02 06:37 UTC, jremen commented on assets/styles/components/_AiWhisperAssistent.scss
> +		padding: 5em 40px;
relative units

2023-08-02 06:37 UTC, jremen commented on assets/styles/components/_AiWhisperAssistent.scss
> +		column-gap: 60px;
relative units

2023-08-02 06:38 UTC, jremen commented on assets/styles/layouts/_ComparePlansNew.scss
> +					padding: 0.25em 0.5625em 0.25em 0.5625em;
padding: 0.25em 0.5625em

2023-08-02 06:38 UTC, jremen commented on assets/styles/layouts/_PricingPrograms.scss
> +					padding: 0.125em 0.5625em 0.125em 0.5625em;
same, padding: 0.125em 0.5625em;

2023-08-02 06:39 UTC, jremen requested changes
multiple changes required, again, relative units, unnecessary high z-index, simplify padding values with same top/bottom and left/right

2023-08-02 07:13 UTC, thujcak commented on assets/styles/components/AnnouncementBar.scss
> +									font-size: 1.4375em;
I just stuck to the design.

2023-08-02 07:23 UTC, thujcak commented on assets/styles/components/AnnouncementBar.scss
> +					z-index: 999;
our header has z-index of 100. I need the element to be at least 1 higher z-index so i use 101.

2023-08-03 11:05 UTC, jremen approved these changes

2023-08-03 11:22 UTC, merged