[2835] PageSpeed: Defer Offscreen Images
QualityUnit/liveagent-theme pull request #1978
Opened 2024-02-28 05:47 UTC by thujcak

**Changes proposed in this Pull Request**
I Stoped loading images when they are not visible

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] My commits follow the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#2835

2024-03-01 12:24 UTC, jremen submitted a review, later dismissed

2024-03-04 10:07 UTC, jremen commented on assets/styles/components/Block.scss
> +			background: transparent url(../images/background__elements.jpg) center center no-repeat;
this must be png at least as we have to change background color sometimes

2024-03-04 10:07 UTC, jremen requested changes
Change JPG to PNG with transparency as we have to change background color sometimes

2024-03-04 14:26 UTC, thujcak commented on assets/styles/components/Block.scss
> +			background: transparent url(../images/background__elements.jpg) center center no-repeat;
it's ok for this element

2024-03-05 07:32 UTC, jremen approved these changes

2024-03-05 07:35 UTC, merged