fix: width of text in video element
QualityUnit/liveagent-theme pull request #201
Opened 2022-06-15 08:24 UTC by rlaco-qualityunit

**Changes proposed in this Pull Request**
Changed video position in section on desktop. Width of text was fixed.

**Testing instructions**
Please check if my solution works as was requested

**Checklist**
- [ ] My code follows the style guidelines of this project
- [ ] My commits follow the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#[502]

2022-06-15 12:09 UTC, jremen commented on assets/styles/components/_BlockVideo.scss
> +						//padding: 0;
Remove commented code

2022-06-15 12:10 UTC, jremen commented on assets/styles/components/_BlockVideo.scss
> +						//#{$pos}: calc(-50vw + 690px - 20px);
Are we sure we want to remove dynamic calculation? If so, remove commented out code. Never leave such code undeleted.

2022-06-15 12:11 UTC, jremen requested changes
Read the comments in code

2022-06-16 05:30 UTC, jremen approved these changes

2022-06-16 06:22 UTC, rlaco-qualityunit commented
due to commit errors, new branch "502_video_element_text_fix" was created

2022-06-16 06:22 UTC, closed without merging