[2126] feat: redesign of item element
QualityUnit/liveagent-theme pull request #238
Opened 2022-06-22 12:35 UTC by Sperthix

**Changes proposed in this Pull Request**
Redesigned item element

**Testing instructions**
Element can be found on [/use-case-scenarios/](http://liveagent.local/use-case-scenarios/)

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] My commits follow the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

**Note**
After deployment is needed to add Learn more link for every item, which contains a link in elementor

Close QualityUnit/web-issues#536

2022-06-23 05:58 UTC, jremen commented on assets/styles/components/_BoxesStars.scss
> +				-webkit-background-clip: text;
No need to use webkit specific properties (except for -webkit-text-fill-color), we are using Autoprefixer on the background. Remove -webkit-background-clip

2022-06-23 06:00 UTC, jremen requested changes

2022-06-23 06:00 UTC, jremen commented on assets/styles/components/_BoxesStars.scss
> +					height: 500px;
Preferably use min-height and em units if possible

2022-06-29 13:29 UTC, jremen submitted a review, later dismissed

2022-07-06 09:39 UTC, mvstepanek approved these changes

2022-07-11 07:02 UTC, merged