[488] Enhancement of Long Texts Element
QualityUnit/liveagent-theme pull request #249
Opened 2022-06-27 13:30 UTC by rlaco-qualityunit

**Changes proposed in this Pull Request**
Block--learnMore changes:
- header styles
- content filter function for add sidebars and new structure
- content filter function for create "zoom in" image with caption from images with links
- content filter function for create gallery from elementor basic gallery

Content filter function for add pros/cons classes to elementor checklists sections and new pros/ const styling

**Testing instructions**
Test landing pages with "long text elements" editable by elementor and new elements:
- sidebar navigation
- sidebars behavior
- image with "zoom in"
- basic gallery
- pros / cons
- small aligned images added by wysiwyg editor

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] My commits follow the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#488

2022-07-06 06:28 UTC, jremen submitted a review, later dismissed

2022-07-11 06:28 UTC, jremen commented
For now, there is an error in layout, because wrapper__wide is set to block at res. above 1024px . Fix it please
![Screenshot 2022-07-11 at 08 28 09](https://user-images.githubusercontent.com/7055428/178202081-32727f0d-86d4-487a-aad4-b534241e1eb0.png)

2022-07-11 06:29 UTC, jremen requested changes
.wrapper__wide is set to display: block instead of flex at 1024px media query, causing bad layout. Fix it.

2022-07-14 12:03 UTC, rlaco-qualityunit commented
> .wrapper__wide is set to display: block instead of flex at 1024px media query, causing bad layout. Fix it.

Are you sure, you have all changes, compiled assets and cleared browser cache? ".wrapper__wide" have correct display in my scss.

2022-07-18 05:25 UTC, jremen approved these changes

2022-07-18 11:26 UTC, mvstepanek approved these changes

2022-07-19 09:25 UTC, merged