[494] feat: pricing shortcode redesign
QualityUnit/liveagent-theme pull request #250
Opened 2022-06-30 18:47 UTC by Sperthix

**Changes proposed in this Pull Request**
Redesigned pricing element, removed unnecessary code.

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] My commits follow the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#494

2022-07-12 08:15 UTC, jremen approved these changes

2022-07-15 06:41 UTC, mvstepanek requested changes

2022-07-15 06:41 UTC, mvstepanek commented on lib/shortcodes/block-pricing.php
> +							<span>Unlimited ticket history</span>
Make the text translatable.

2022-07-15 06:41 UTC, mvstepanek commented on lib/shortcodes/block-pricing.php
> +					<a href="/trial/'" class="Button Button--outline">
Even URLs should be translatable.

2022-07-15 06:41 UTC, mvstepanek commented on lib/shortcodes/block-pricing.php
> +		<div class="BlockPricing__container__item">
Maybe try to create loop. Because now you have four times almost the same code. Differences are just texts and numbers.

2022-07-15 06:41 UTC, mvstepanek commented on assets/styles/components/_BlockPricing.scss
> +		@include color(background-color, secondary-background);
No more is necessary to use this way for colours. Just use variable `background-color:  $secondary-background;`

2022-07-15 06:41 UTC, mvstepanek commented on assets/styles/components/_BlockPricing.scss
> +						// white-space: pre-wrap;
Remove it.

2022-07-15 06:41 UTC, mvstepanek commented on assets/styles/components/_BlockPricing.scss
> +						content: "month";
Don't use it in CSS. Because we can't translate it then.

2022-07-18 08:09 UTC, mvstepanek commented on lib/shortcodes/block-pricing.php
> +			'title1' => '',
Add Default Values.

2022-07-18 15:30 UTC, Sperthix commented on lib/shortcodes/block-pricing.php
> +			'title1' => '',
done

2022-07-19 11:45 UTC, mvstepanek approved these changes

2022-07-19 11:47 UTC, merged