[595] feat: add website screenshot to directory
QualityUnit/liveagent-theme pull request #298
Opened 2022-07-13 12:32 UTC by mvstepanek

**Changes proposed in this Pull Request**
Add URLsLab screenshot to Directory
Add link to company website in perex

**Testing instructions**
E.g. [this URL](http://liveagent.local/directory/airbus-help-desk-contacts/).

**Checklist**
- [ ] My code follows the style guidelines of this project
- [ ] My commits follow the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#595

2022-07-14 08:14 UTC, jremen commented on assets/styles/pages/Directory.scss
> +			display: none !important;
If important not required, do not use it

2022-07-14 08:14 UTC, jremen commented on assets/styles/pages/Directory.scss
> +		margin-bottom: 45px;
Use relative units

2022-07-14 08:15 UTC, jremen requested changes
Replace pixels with EMs

2022-07-14 11:07 UTC, mvstepanek commented on assets/styles/pages/Directory.scss
> +			display: none !important;
Unfortunately, it is necessary.

2022-07-14 11:08 UTC, mvstepanek commented on assets/styles/pages/Directory.scss
> +		margin-bottom: 45px;
Fixed.

2022-07-18 07:56 UTC, jremen submitted a review, later dismissed

2022-07-19 08:58 UTC, jremen approved these changes

2022-07-19 09:26 UTC, merged