FAQ redesign
QualityUnit/liveagent-theme pull request #32
Opened 2022-04-29 18:49 UTC by Sperthix

**Changes proposed in this Pull Request**
reworked ExtraFaq design and other 2 faqs designs were reworked to fit ExtraFaq new design in LiveAgent
added few wrapping div`s
changed classnames from "ExtraFaq" to univerzal "Faq"

**Checklist**
- [✓] My code follows the style guidelines of this project
- [✓] My commits follow the style guidelines of this project
- [✓] I have performed a self-review of my code
- [✓] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#[386]

2022-05-02 09:48 UTC, mvstepanek requested changes
Also, you can try to rewrite JSON code for schema.org into HTML structure. Check the following article [link](https://schema.org/docs/gs.html) and [link](https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data).

2022-05-02 09:48 UTC, mvstepanek commented on assets/styles/components/_ExtraFaq.scss
> +		padding: 0 0.5rem;
Don't use `rem` where it is unnecessary. Check the difference between `em` and `rem` and implement it correctly across all changed files. If you need to explain it, Jozef can help you.

2022-05-02 09:48 UTC, mvstepanek commented on assets/styles/components/_ExtraFaq.scss
> +			position: relative;
For the following lines, try to find better solutions. For example, absolute position for pseudoelement and left padding for heading. Then, it will be more straightforward.

2022-05-02 09:48 UTC, mvstepanek commented on assets/styles/components/_ExtraFaq.scss
> +				overflow: visible !important;
Check documentation for what `overflow: visible` exists. Then remove it from here. Especially with `!important`. You need to have a perfect reason to use `!important`.

2022-05-02 09:48 UTC, mvstepanek commented on assets/styles/components/_ExtraFaq.scss
> +		div.Faq__outer-wrapper {
Use only class names without `div`. `div` you can use only when you need to write stronger code because you need to overwrite something.

2022-05-02 09:48 UTC, mvstepanek commented on assets/styles/components/_ExtraFaq.scss
> +			background: linear-gradient(180deg, rgba(250, 149, 49, 1) 0%, rgba(255, 255, 255, 1) 70%, rgba(255, 255, 255, 1) 100%);
Just `rgb` if there is no opacity.

2022-05-02 09:48 UTC, mvstepanek commented on lib/shortcodes/extra-faq.php
> +		'faq'
Please don't change this line, we need to keep the old shortcode, and we want to change only design a related structure. The same is for other shortcodes.

2022-05-02 09:48 UTC, mvstepanek commented on lib/shortcodes/extra-faq.php
> +add_shortcode( 'faq', 'ms_faq' );
Please don't change this line, we need to keep the old shortcode, and we want to change only design a related structure. The same is for other shortcodes.

2022-05-02 09:48 UTC, mvstepanek commented on lib/shortcodes/extra-faq.php
> +function ms_faq( $atts ) {
Please don't change this line, we need to keep the old shortcode, and we want to change only design a related structure. The same is for other shortcodes.

2022-05-02 09:48 UTC, mvstepanek commented on lib/shortcodes/extra-faq.php
>  			<?php if ( $atts['question-1'] ) { ?>
You can try to use the `for` cycle. To minify the code. The same for other shortcodes.

2022-05-09 08:25 UTC, jremen approved these changes

2022-05-09 08:29 UTC, jremen requested changes

2022-05-09 08:29 UTC, jremen commented on assets/styles/components/_ExtraFaq.scss
> +	display: flex !important;
why we are using flexbox here if all answers and questions go after each other in a column?

2022-05-09 08:29 UTC, jremen commented on assets/styles/components/_ExtraFaq.scss
> +					width: 100%;
use @include square(100%) mixin

2022-05-09 08:29 UTC, jremen commented on lib/shortcodes/extra-faq.php
> -				<div class="ExtraFaq__item">
Can't we rewrite all of this code below to one loop as in previous files?

2022-05-09 09:45 UTC, jremen commented on assets/styles/components/_ExtraFaq.scss
> +					width: 100%;
Fixed

2022-05-09 09:52 UTC, Sperthix commented on assets/styles/components/_ExtraFaq.scss
> +	display: flex !important;
there are 2 in 1 row, therefore 1 faq item has 45% of total width, on smaller screens it gets 100% width and then they all are in 1 column

2022-05-09 10:02 UTC, jremen commented on assets/styles/components/_ExtraFaq.scss
> +					width: 100%;
ok

2022-05-11 11:27 UTC, mvstepanek approved these changes

2022-05-11 11:33 UTC, jremen approved these changes

2022-05-11 11:35 UTC, merged