[425] Social media page redesign
QualityUnit/liveagent-theme pull request #325
Opened 2022-07-19 06:33 UTC by rlaco-qualityunit

**Changes proposed in this Pull Request**
Describe what was changed in the Pull Request

**Testing instructions**
Describe how and what should be tested by a Tester

**Checklist**
- [ ] My code follows the style guidelines of this project
- [ ] My commits follow the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#425

2022-07-21 06:19 UTC, jremen submitted a review, later dismissed

2022-07-21 08:18 UTC, mvstepanek approved these changes

2022-07-21 12:13 UTC, mvstepanek requested changes
Don't modify current height of video blocks.

2022-07-25 13:32 UTC, mvstepanek approved these changes

2022-07-26 09:51 UTC, merged