[530] Coupon Banner
QualityUnit/liveagent-theme pull request #345
Opened 2022-07-21 14:29 UTC by rlaco-qualityunit

**Changes proposed in this Pull Request**
Describe what was changed in the Pull Request

**Testing instructions**
Describe how and what should be tested by a Tester

**Checklist**
- [ ] My code follows the style guidelines of this project
- [ ] My commits follow the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#530

2022-07-25 05:06 UTC, jremen commented on assets/styles/components/_BlockCoupon.scss
> +			path {
use the fill on whole SVG

2022-07-25 05:07 UTC, jremen commented on assets/styles/components/_BlockCoupon.scss
> +			background-position: center center;
Why is this here when no color or image is defined?

2022-07-25 05:08 UTC, jremen requested changes
Make fixes according to the comments

2022-07-25 07:38 UTC, rlaco-qualityunit commented on assets/styles/components/_BlockCoupon.scss
> +			background-position: center center;
Image is defined by user as overlay in Elementor block and is not necessary to display it on small displays.
(gradient is defined in section CSS by default and can be overwritten by user in Elementor)

2022-07-25 07:38 UTC, rlaco-qualityunit commented on assets/styles/components/_BlockCoupon.scss
> +			path {
fixed

2022-07-25 07:44 UTC, rlaco-qualityunit commented
> Make fixes according to the comments

@jremen done

2022-07-28 09:52 UTC, mvstepanek approved these changes

2022-08-03 11:16 UTC, merged