[496] feat: added design for help desk page
QualityUnit/liveagent-theme pull request #387
Opened 2022-08-03 00:55 UTC by Sperthix

**Changes proposed in this Pull Request**
Changed design of help desk landing page as in [figma file](https://www.figma.com/file/MyPe8HfTYEoOzmxMpdJQ1h/LA-WEB-RfD---Helpdesk?node-id=139%3A128). Added design for solutions element separatly.

**Testing instructions**
Please chceck design in various browsers on [this](http://liveagent.local/help-desk-software-redesign/) page

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] My commits follow the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#[496]

2022-08-04 05:52 UTC, jremen requested changes

2022-08-04 05:52 UTC, jremen commented on assets/styles/components/_BlockSolution.scss
> +		max-width: 1400px !important;
if possible, use $breakpoint-desktop-box instead. We have max width 1380px united across all web

2022-08-04 05:52 UTC, jremen commented on assets/styles/components/_BlockSolution.scss
> +			background: rgb(255, 255, 255);
background: $white

2022-08-04 05:52 UTC, jremen commented on assets/styles/components/_BlockSolution.scss
> +			width: 100%;
@include square(100%);
border-radius: $border-radius-16

2022-08-04 05:52 UTC, jremen commented on assets/styles/components/_BlockSolution.scss
> +			width: 29% !important;
avoid important if possible (most of time, it is)

2022-08-04 05:52 UTC, jremen commented on assets/styles/layouts/_HelpDesk.scss
> +		max-width: 1380px !important;
breakpoint-desktop-box, remove important

2022-08-05 10:01 UTC, jremen approved these changes

2022-08-05 10:02 UTC, jremen approved these changes

2022-08-05 10:25 UTC, mvstepanek approved these changes

2022-08-09 12:24 UTC, merged