[792] Template blog header dom updated
QualityUnit/liveagent-theme pull request #664
Opened 2022-10-18 19:13 UTC by rlaco-qualityunit

**Changes proposed in this Pull Request**
Template blog header DOM updated according new elementor optimized DOM Output.

**Testing instructions**
Check [Email management software](http://liveagent.local/email-management-software/) page header and comapre it with hedaders on landing pages.

**Checklist**
- [ ] My code follows the style guidelines of this project
- [ ] My commits follow the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#792

2022-10-26 10:39 UTC, jremen commented
@rlaco-qualityunit 

Not fixed well. Please copy structure of the actual home header ie. in https://www.liveagent.com/help-desk-software/ an replace with variables

![Screenshot 2022-10-26 at 12 38 13](https://user-images.githubusercontent.com/7055428/198005713-461249a5-a268-4023-acb4-0204671aae6a.png)

2022-10-26 10:40 UTC, jremen requested changes
Fix by copying actual header ie from /help-desk-software/ and replace with variables.

If working locally, check if you have optimized DOM turned on in Elementor
![Screenshot 2022-10-26 at 12 38 13](https://user-images.githubusercontent.com/7055428/198005988-f463617b-89bb-42bc-84bb-37463f7ec23b.png)

2022-10-27 12:04 UTC, rlaco-qualityunit commented
> Fix by copying actual header ie from /help-desk-software/ and replace with variables.
> 
> If working locally, check if you have optimized DOM turned on in Elementor ![Screenshot 2022-10-26 at 12 38 13](https://user-images.githubusercontent.com/7055428/198005988-f463617b-89bb-42bc-84bb-37463f7ec23b.png)

@jremen Fixed. Problem was in missing elementor styles.

2022-11-04 12:20 UTC, jremen approved these changes

2022-11-04 12:43 UTC, merged