[985] Learn-more arrow updates
QualityUnit/liveagent-theme pull request #902
Opened 2022-12-13 15:23 UTC by rlaco-qualityunit

**Changes proposed in this Pull Request**
Describe what was changed in the Pull Request

**Testing instructions**
Describe how and what should be tested by a Tester

**Checklist**
- [ ] My code follows the style guidelines of this project
- [ ] My commits follow the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#985

2022-12-14 08:09 UTC, jremen requested changes
WOuld be better to use DOM content filter and insert SVG icon inside //div[contains(@class, 'learn-more')] a

2022-12-15 09:46 UTC, jremen requested changes
Rewrite rather using new svg icons functionality by looking for .learn-more a element and inserting icons.svg#arrow-right

2023-01-03 12:04 UTC, rlaco-qualityunit commented
> Rewrite rather using new svg icons functionality by looking for .learn-more a element and inserting icons.svg#arrow-right

Changes was made.

2023-01-09 09:02 UTC, jremen approved these changes

2023-01-09 12:40 UTC, merged